# .github/workflows/deploy.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Create Firebase config file
        run: |
          echo "import { initializeApp } from 'firebase/app';" > src/firebase.js
          echo "import { getAuth } from 'firebase/auth';" >> src/firebase.js
          echo "import { getFirestore } from 'firebase/firestore';" >> src/firebase.js
          echo "" >> src/firebase.js
          echo "const firebaseConfig = {" >> src/firebase.js
          echo "  apiKey: '${{ secrets.REACT_APP_API_KEY }}'," >> src/firebase.js
          echo "  authDomain: '${{ secrets.REACT_APP_AUTH_DOMAIN }}'," >> src/firebase.js
          echo "  projectId: '${{ secrets.REACT_APP_PROJECT_ID }}'," >> src/firebase.js
          echo "  storageBucket: '${{ secrets.REACT_APP_STORAGE_BUCKET }}'," >> src/firebase.js
          echo "  messagingSenderId: '${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}'," >> src/firebase.js
          echo "  appId: '${{ secrets.REACT_APP_APP_ID }}'" >> src/firebase.js
          echo "};" >> src/firebase.js
          echo "" >> src/firebase.js
          echo "const app = initializeApp(firebaseConfig);" >> src/firebase.js
          echo "export const auth = getAuth(app);" >> src/firebase.js
          echo "export const db = getFirestore(app);" >> src/firebase.js
      
      - name: Print created file for debugging
        run: cat src/firebase.js

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GEOQUEST_1C461 }}'
          channelId: live
          projectId: 'geoquest-1c461' # Byt ut mot ditt projekt-ID
